export interface ZodiacSignData {
  name: string;
  symbol: string;
  dates: string;
  element: 'Fire' | 'Earth' | 'Air' | 'Water';
  modality: 'Cardinal' | 'Fixed' | 'Mutable';
  rulingPlanet: string;
  traits: string[];
  description: string;
  strengths: string[];
  challenges: string[];
  seasonalMeaning: string;
}

export const ZODIAC_SIGNS: Record<string, ZodiacSignData> = {
  aries: {
    name: 'Aries',
    symbol: '♈',
    dates: 'March 21 – April 19',
    element: 'Fire',
    modality: 'Cardinal',
    rulingPlanet: 'Mars',
    traits: ['Initiating', 'Direct', 'Courageous', 'Independent'],
    description: 'Aries marks the beginning of the zodiac and the start of spring in the Northern Hemisphere. This cardinal fire sign embodies the energy of new beginnings, initiative, and bold action. There is a directness to Aries energy—a willingness to go first, to pioneer, to start what others might hesitate to begin.',
    strengths: [
      'The capacity to initiate and take action',
      'Natural courage when facing the unknown',
      'Honest and direct communication',
      'The energy to champion causes and people',
    ],
    challenges: [
      'Impatience with slower processes',
      'Tendency to start more than can be finished',
      'Learning when to yield versus push forward',
      'Balancing independence with collaboration',
    ],
    seasonalMeaning: 'Aries season arrives with the spring equinox, when daylight begins to outpace darkness. It is a time of emergence after winter\'s rest—seeds pushing through soil, energy returning after dormancy.',
  },
  taurus: {
    name: 'Taurus',
    symbol: '♉',
    dates: 'April 20 – May 20',
    element: 'Earth',
    modality: 'Fixed',
    rulingPlanet: 'Venus',
    traits: ['Grounded', 'Sensual', 'Patient', 'Reliable'],
    description: 'Taurus follows Aries in the zodiac, moving from initiation to cultivation. This fixed earth sign is concerned with what can be built, grown, and sustained over time. There is a deep appreciation for the material world—not as acquisition, but as the tangible experience of being alive.',
    strengths: [
      'Patience and persistence with long-term goals',
      'Deep appreciation for beauty and quality',
      'Reliability and steadfastness',
      'Connection to physical senses and embodiment',
    ],
    challenges: [
      'Resistance to necessary change',
      'Difficulty letting go of what no longer serves',
      'Tendency toward comfort over growth',
      'Stubbornness when flexibility is needed',
    ],
    seasonalMeaning: 'Taurus season unfolds in mid-spring when the world is in full bloom. It is a time of enjoying what has emerged, of slowing down to appreciate growth rather than forcing it.',
  },
  gemini: {
    name: 'Gemini',
    symbol: '♊',
    dates: 'May 21 – June 20',
    element: 'Air',
    modality: 'Mutable',
    rulingPlanet: 'Mercury',
    traits: ['Curious', 'Communicative', 'Adaptable', 'Quick-thinking'],
    description: 'Gemini brings movement and exchange after the solidity of Taurus. This mutable air sign is associated with communication, learning, and the endless pursuit of interesting information. The symbol of the twins speaks to the multiplicity within—the capacity to see many sides, hold many interests, and move between different modes of being.',
    strengths: [
      'Natural facility with language and communication',
      'Intellectual curiosity and rapid learning',
      'Adaptability in changing circumstances',
      'Ability to connect ideas and people',
    ],
    challenges: [
      'Difficulty with sustained focus on one thing',
      'Tendency to scatter energy across too many interests',
      'Learning to go deep rather than wide',
      'Following through on commitments',
    ],
    seasonalMeaning: 'Gemini season bridges spring and summer, a time of increasing social activity and exchange before the solstice. The days lengthen and conversations grow.',
  },
  cancer: {
    name: 'Cancer',
    symbol: '♋',
    dates: 'June 21 – July 22',
    element: 'Water',
    modality: 'Cardinal',
    rulingPlanet: 'Moon',
    traits: ['Nurturing', 'Intuitive', 'Protective', 'Emotionally intelligent'],
    description: 'Cancer begins at the summer solstice, the longest day, and turns inward even as the world faces outward. This cardinal water sign is ruled by the Moon and concerned with matters of home, family, and emotional security. There is a protective quality to Cancer—a desire to create safe harbors for self and loved ones.',
    strengths: [
      'Deep emotional intelligence and intuition',
      'Capacity to nurture and create belonging',
      'Strong connection to memory and history',
      'Protective care for vulnerable people and things',
    ],
    challenges: [
      'Difficulty releasing past hurts',
      'Tendency toward moodiness and indirect communication',
      'Over-protection that limits growth',
      'Balancing care for others with self-care',
    ],
    seasonalMeaning: 'Cancer season begins at the peak of light and marks a turn toward home, rest, and tending to inner life even as summer activities peak externally.',
  },
  leo: {
    name: 'Leo',
    symbol: '♌',
    dates: 'July 23 – August 22',
    element: 'Fire',
    modality: 'Fixed',
    rulingPlanet: 'Sun',
    traits: ['Creative', 'Generous', 'Warm', 'Confident'],
    description: 'Leo arrives in the height of summer, ruled by the Sun and embodying solar qualities of warmth, creativity, and self-expression. This fixed fire sign is associated with the heart—both the courage that the heart represents and the capacity to generate warmth for others. Leo energy is generous and wants to share what it creates.',
    strengths: [
      'Natural creativity and self-expression',
      'Generosity of spirit and warmth',
      'Courage to be visible and take creative risks',
      'Ability to inspire and lead through presence',
    ],
    challenges: [
      'Need for external validation and recognition',
      'Difficulty stepping back from center stage',
      'Learning to receive as well as give',
      'Balancing confidence with humility',
    ],
    seasonalMeaning: 'Leo season unfolds in the full heat of summer, when the sun dominates and life is lived visibly, outdoors, and with vitality.',
  },
  virgo: {
    name: 'Virgo',
    symbol: '♍',
    dates: 'August 23 – September 22',
    element: 'Earth',
    modality: 'Mutable',
    rulingPlanet: 'Mercury',
    traits: ['Analytical', 'Practical', 'Helpful', 'Discerning'],
    description: 'Virgo marks the transition from summer abundance to autumn harvest. This mutable earth sign is concerned with refinement, improvement, and service. There is a quality of discernment to Virgo—the ability to see what needs attention, what can be made better, and how to be useful in practical ways.',
    strengths: [
      'Attention to detail and quality',
      'Practical problem-solving abilities',
      'Desire to be genuinely helpful',
      'Ability to improve and refine processes',
    ],
    challenges: [
      'Tendency toward self-criticism and perfectionism',
      'Difficulty accepting "good enough"',
      'Over-analysis that prevents action',
      'Learning to receive help as well as give it',
    ],
    seasonalMeaning: 'Virgo season coincides with late summer harvest, a time of sorting, preserving, and preparing. It is practical work that requires discrimination.',
  },
  libra: {
    name: 'Libra',
    symbol: '♎',
    dates: 'September 23 – October 22',
    element: 'Air',
    modality: 'Cardinal',
    rulingPlanet: 'Venus',
    traits: ['Diplomatic', 'Aesthetic', 'Partnership-oriented', 'Fair-minded'],
    description: 'Libra begins at the autumn equinox, when day and night reach equal length. This cardinal air sign is concerned with balance, harmony, and relationship. The scales symbolize the weighing of perspectives, the seeking of fairness, and the understanding that we exist in relation to others.',
    strengths: [
      'Natural diplomacy and mediation abilities',
      'Strong aesthetic sense and appreciation for beauty',
      'Commitment to fairness and justice',
      'Skill in partnership and collaboration',
    ],
    challenges: [
      'Indecision from seeing too many sides',
      'Tendency to avoid conflict at personal cost',
      'Over-dependence on others\' approval',
      'Learning to prioritize self alongside others',
    ],
    seasonalMeaning: 'Libra season arrives with the equinox, a moment of perfect balance before the descent into darker months. It is a natural time for relationship and recalibration.',
  },
  scorpio: {
    name: 'Scorpio',
    symbol: '♏',
    dates: 'October 23 – November 21',
    element: 'Water',
    modality: 'Fixed',
    rulingPlanet: 'Pluto (traditional: Mars)',
    traits: ['Intense', 'Investigative', 'Transformative', 'Loyal'],
    description: 'Scorpio moves into the darkening season, when leaves fall and what was hidden begins to show. This fixed water sign is associated with depth, transformation, and the courage to face what lies beneath surfaces. Scorpio energy is not afraid of intensity—it seeks truth even when truth is uncomfortable.',
    strengths: [
      'Capacity for deep emotional intimacy',
      'Investigative and perceptive abilities',
      'Loyalty and commitment in relationships',
      'Ability to transform through crisis',
    ],
    challenges: [
      'Difficulty with vulnerability and trust',
      'Tendency toward obsession or fixation',
      'Learning to release control',
      'Processing intensity without being consumed',
    ],
    seasonalMeaning: 'Scorpio season coincides with late autumn, when death is visible in fallen leaves and shortened days. It is a time for composting what has ended.',
  },
  sagittarius: {
    name: 'Sagittarius',
    symbol: '♐',
    dates: 'November 22 – December 21',
    element: 'Fire',
    modality: 'Mutable',
    rulingPlanet: 'Jupiter',
    traits: ['Adventurous', 'Philosophical', 'Optimistic', 'Expansive'],
    description: 'Sagittarius follows the depth of Scorpio with expansion and exploration. This mutable fire sign is associated with the search for meaning, the love of learning, and the desire to experience life broadly. The archer aims at distant targets—philosophies, places, and ideas that enlarge understanding.',
    strengths: [
      'Natural optimism and enthusiasm',
      'Love of learning and exploring',
      'Ability to find meaning in experience',
      'Generosity of vision and spirit',
    ],
    challenges: [
      'Restlessness and difficulty with commitment',
      'Tendency to overlook details for the big picture',
      'Bluntness that can wound unintentionally',
      'Learning to develop depth alongside breadth',
    ],
    seasonalMeaning: 'Sagittarius season carries through late autumn into early winter, a time when physical travel may slow but mental exploration can flourish.',
  },
  capricorn: {
    name: 'Capricorn',
    symbol: '♑',
    dates: 'December 22 – January 19',
    element: 'Earth',
    modality: 'Cardinal',
    rulingPlanet: 'Saturn',
    traits: ['Ambitious', 'Disciplined', 'Responsible', 'Enduring'],
    description: 'Capricorn begins at the winter solstice, the darkest point from which light begins to return. This cardinal earth sign is associated with structure, achievement, and the wisdom that comes from experience. There is a quality of earned authority to Capricorn—the understanding that meaningful things require time and effort.',
    strengths: [
      'Capacity for sustained effort toward goals',
      'Natural understanding of structure and systems',
      'Reliability and responsibility',
      'Wisdom from experience and lessons learned',
    ],
    challenges: [
      'Tendency toward pessimism or excessive caution',
      'Difficulty allowing pleasure and play',
      'Over-identification with work and achievement',
      'Learning to value process alongside outcome',
    ],
    seasonalMeaning: 'Capricorn season begins in the depth of winter, when survival requires planning, resources, and endurance. It is serious time that rewards preparation.',
  },
  aquarius: {
    name: 'Aquarius',
    symbol: '♒',
    dates: 'January 20 – February 18',
    element: 'Air',
    modality: 'Fixed',
    rulingPlanet: 'Uranus (traditional: Saturn)',
    traits: ['Innovative', 'Humanitarian', 'Independent', 'Visionary'],
    description: 'Aquarius arrives in the heart of winter with energy that looks toward the future. This fixed air sign is associated with innovation, community, and the understanding that individual well-being is connected to collective well-being. Aquarius energy questions conventions and imagines alternatives.',
    strengths: [
      'Innovative and original thinking',
      'Commitment to humanitarian ideals',
      'Independence of thought and action',
      'Ability to see systems and patterns',
    ],
    challenges: [
      'Emotional detachment as a defense',
      'Difficulty with intimacy and vulnerability',
      'Rebelliousness for its own sake',
      'Learning to work within systems while changing them',
    ],
    seasonalMeaning: 'Aquarius season falls in deep winter when community and cooperation become essential for survival. Looking toward the future together.',
  },
  pisces: {
    name: 'Pisces',
    symbol: '♓',
    dates: 'February 19 – March 20',
    element: 'Water',
    modality: 'Mutable',
    rulingPlanet: 'Neptune (traditional: Jupiter)',
    traits: ['Intuitive', 'Compassionate', 'Imaginative', 'Sensitive'],
    description: 'Pisces concludes the zodiac, the mutable water sign that dissolves boundaries before the cycle begins again with Aries. There is a quality of completion and transcendence to Pisces—the understanding that separation is illusion and compassion is the natural response to shared humanity.',
    strengths: [
      'Deep intuition and sensitivity',
      'Natural compassion and empathy',
      'Rich imagination and creativity',
      'Spiritual awareness and connection',
    ],
    challenges: [
      'Boundary issues and over-absorption of others\' feelings',
      'Tendency toward escapism',
      'Difficulty with practical matters',
      'Learning discernment alongside compassion',
    ],
    seasonalMeaning: 'Pisces season marks late winter, when snow melts and boundaries dissolve before the new beginning. A liminal time between endings and beginnings.',
  },
};
